csarrazi/CsaGuzzleBundle

src/Resources/doc/configuration_reference.md

[RFR] updating configuration reference

---

composer.lock
src/DataCollector/GuzzleCollector.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php

* Fixed issue with logger format
* Improved URI rendering in profiler page (Fixes #44)

Fixed small issues.

---

.travis.yml

Updated build matrix to build against both lowest and latest dependencies

Updated travis build matrix

---

src/DependencyInjection/CsaGuzzleExtension.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Fixes an issue with subscribers not being correctly added to client when using custom subscribers.

Fixed missing custom subscribers when using configuration

---

.travis.yml
src/DependencyInjection/CsaGuzzleExtension.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Fixes an issue with default subscribers not correctly being added because of the previous fix.

Fixed issue with default subscribers not being added automatically

---

.travis.yml
src/Resources/views/Calls/call.html.twig
src/Resources/views/Calls/macros.html.twig
src/Twig/Extension/GuzzleExtension.php

Added support for web debug toolbar link in the profiler

---

composer.json
composer.lock
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/GuzzleHttp/Middleware.php
src/Resources/config/mock.xml
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php
src/Tests/Fixtures/mocks/GET____?____9e9a30563f33dce7531caf0b1e14f6c4.txt
src/Tests/GuzzleHttp/Cache/MockStorageAdapterTest.php

Add the ability to record http calls, then to use them as mock in tests.

Mock http calls

---

README.md
src/Resources/doc/tests_mock_http_requests.md

See https://github.com/csarrazi/CsaGuzzleBundle/issues/74

Create documentation for mocks

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Added support for client service aliasing

---

src/DependencyInjection/CsaGuzzleExtension.php

Small refactoring for processLoggerConfiguration method.

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Resources/doc/clients.md
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Possibility to make lazy clients

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

This PR fixes #89.
The handler is now no longer overwritten when middleware are injected.

Fixed issue with custom handler being overridden in the compiler pass

---

.travis.yml
src/GuzzleHttp/Cache/DoctrineAdapter.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/GuzzleHttp/Middleware.php

The issue seems to come from the fact that the provided phpunit is broken in the PHP7 build.

Fixed issues with PhpUnit and PHP7

---

src/DataCollector/GuzzleCollector.php
src/HttpFoundation/StreamResponse.php
src/Resources/config/middleware.xml
src/Resources/views/Collector/guzzle.html.twig

Also add api calls total time in profiler bar and profiler menu

Fix issue #110 about cached request not handled by history

---

.travis.yml
src/DependencyInjection/CompilerPass/MiddlewarePass.php

Added class in DefinitionDecorator, as it breaks with Symfony < 2.8.

---

composer.lock
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

This PR is the implementation of #124

Added possibility to configure mock storage header blacklist

---

.github/PULL_REQUEST_TEMPLATE.md

| Bug fix?      | [yes|no]
| New feature?  | [yes|no]
| BC breaks?    | [yes|no]
| Deprecations? | [yes|no]
| Tests pass?   | [yes|no]
| Fixed tickets | [comma separated list of tickets fixed by the PR]

Added github PR template

---

.travis.yml
appveyor.yml
composer.json
composer.lock
src/GuzzleHttp/Cache/DoctrineAdapter.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/GuzzleHttp/Cache/NamingStrategy/AbstractNamingStrategy.php
src/GuzzleHttp/Cache/NamingStrategy/HashNamingStrategy.php
src/GuzzleHttp/Cache/NamingStrategy/LegacyNamingStrategy.php
src/GuzzleHttp/Cache/NamingStrategy/NamingStrategyInterface.php
src/GuzzleHttp/Cache/NamingStrategy/SubfolderNamingStrategy.php
src/Tests/GuzzleHttp/Cache/MockStorageAdapterTest.php

| Fixed tickets | #130
Refactored naming strategies for mock and cache middleware, and added support for subfolder naming strategy. Should fix #130.

Improved mock middleware

---

composer.json
composer.lock

Fixed issue with web profiler bundle version

---

composer.json
composer.lock
src/DataCollector/GuzzleCollector.php
src/Resources/views/Calls/list.html.twig
src/Resources/views/Calls/macros.html.twig
src/Tests/DataCollector/GuzzleCollectorTest.php

Add cURL command dump in profiler

---

src/GuzzleHttp/Middleware/StopwatchMiddleware.php
src/Tests/GuzzleHttp/Middleware/StopwatchMiddlewareTest.php

Do not number the first request in the stopwatch

---

src/Resources/doc/install.md

| Bug fix?      | [no]
| Fixed tickets | [Doc typo]

Symfony3.1 depreciation

---

src/GuzzleHttp/Middleware.php

| BC breaks?    | yes
| Fixed tickets |

Fixed Middleware using deprecated StorageAdapterInterface interface.

---

src/Resources/doc/clients.md
src/Resources/doc/middleware.md

| Bug fix?      | [no]
| Fixed tickets | [N/A]
Hi Charles :)
Just adding some details to client creation, especially for YAML format.

[RFR] Updating client creation documentation

---

src/Cache/MockStorageAdapter.php
src/DataCollector/GuzzleCollector.php
src/GuzzleHttp/Middleware.php
src/GuzzleHttp/Middleware/HistoryMiddleware.php
tests/DataCollector/GuzzleCollectorTest.php
tests/GuzzleHttp/Middleware/HistoryMiddlewareTest.php
tests/GuzzleHttp/MiddlewareTest.php

Ignore partial transactions

---

appveyor.yml
composer.lock
src/DataCollector/GuzzleCollector.php
src/GuzzleHttp/Middleware/MockMiddleware.php
tests/GuzzleHttp/Middleware/MockMiddlewareTest.php

| Fixed tickets | #164 
The issue came from the MockMiddleware, which used to return a RejectedPromise instead of throwing an exception.
I also refactored a few lines in the GuzzleCollector, in order to simplify some code. Fixes #164

Fixed missing method error in GuzzleCollector

---

src/Resources/meta/LICENSE

Update LICENSE to Apache License 2.0

---

composer.json
composer.lock
src/DataCollector/GuzzleCollector.php
src/GuzzleHttp/Middleware.php
src/Resources/config/collector.xml
src/Resources/config/middleware.xml

| Deprecations? | yes
This PR removes the ExpressionLanguage as a dependency.

Removed ExpressionLanguage as a dependency

---

src/DependencyInjection/CsaGuzzleExtension.php
src/Resources/config/collector.xml

GuzzleCollector :: Argument 1 is "max body size"

---

composer.json
composer.lock
src/Cache/PsrAdapter.php
tests/Cache/DoctrineAdapterTest.php
tests/Cache/MockStorageAdapterTest.php
tests/Cache/PsrAdapterTest.php
tests/GuzzleHttp/Cache/DoctrineAdapterTest.php
tests/GuzzleHttp/Cache/MockStorageAdapterTest.php

Implemented PSR-6 cache and refactored cache tests

---

composer.json
composer.lock
src/DataCollector/GuzzleCollector.php
tests/DataCollector/GuzzleCollectorTest.php

| BC breaks?    | no, i guess
| Fixed tickets | https://github.com/csarrazi/CsaGuzzleBundle/issues/178

Issue/178 Make cuzzle optional

---

src/Resources/doc/event_subscribers.md

| Tests pass?   | no
| Fixed tickets | ø

Precise the subscribers documentation

---

composer.json
composer.lock

Suggest tolerance/tolerance

---

README.md
src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Resources/doc/middleware.md
tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

| BC breaks?    | yes
| Fixed tickets | #194 

Forbid use of middleware blacklisting along with whitelisting

---

tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

Added new test for whitelist and blacklist for Middleware Pass

---

composer.json
composer.lock

Updated branch aliases

---

src/DependencyInjection/CsaGuzzleExtension.php
tests/DependencyInjection/CsaGuzzleExtensionTest.php

Fixed issue with debug middleware being added even when disabled

---

.travis.yml
appveyor.yml
composer.json
composer.lock

Removed support for PHP 5.5 and added support for PHP 7.1

---

composer.json
composer.lock
src/DataCollector/GuzzleCollector.php
src/DependencyInjection/CsaGuzzleExtension.php

Symfony 4 and Flex compatibility

---

composer.json
src/DataCollector/GuzzleCollector.php

| Bug fix?      | [yes]
| Fixed tickets | [none]

Make bundle Symfony 3.4 compatible.

---

src/DependencyInjection/CsaGuzzleExtension.php

Adds missing setPublic(true)

---

src/Resources/config/mock.xml

Fix namespace MockStorageAdapter

---

README.md
src/DataCollector/GuzzleCollector.php
src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Resources/doc/configuration_reference.md
src/Resources/doc/install.md
tests/DependencyInjection/CsaGuzzleExtensionTest.php

Implemented aliasing feature for autowiring

---

composer.json
composer.lock

Added asset component in suggests section of composer file

---

src/Resources/doc/middleware.md

| Bug fix?      | documentation only

document middleware class service definition

---

composer.json
composer.lock
src/Twig/Extension/GuzzleExtension.php

| Bug fix?      | [no]
| BC breaks?    | yes]
| Deprecations? | [yes]
| Fixed tickets | []

fix twig extension deprecation (since Twig 2.7).

---

composer.json
src/Resources/views/Collector/guzzle.html.twig

Fix deprecation with twig 2.10.0

---

src/DependencyInjection/CsaGuzzleExtension.php

| Fixed tickets | N/A
Makes CI green again.
Can you configure `master` to require the checks to pass before allowing to merge a PR?

Apply StyleCI code style patch

---

UPGRADE.md

Add upgrade info for 2.x to 3.0

---

.travis.yml
composer.json

Allow PHP 8.0
