csarrazi/CsaGuzzleBundle

UPGRADE.md
src/DependencyInjection/CompilerPass/SubscriberPass.php
src/DependencyInjection/Configurator/ClientConfigurator.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Factory/ClientFactory.php
src/Resources/config/factory.xml
src/Resources/doc/clients.md
src/Resources/doc/event_subscribers.md
src/Tests/DependencyInjection/CompilerPass/SubscriberPassTest.php
src/Tests/DependencyInjection/Configurator/ClientConfiguratorTest.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Alright, here's a rough implementation for tagging existing Guzzle clients. Here's how it works:
1. Tag a service with `csa_guzzle.client` (with optional `subscribers="foo, bar, baz"` attribute);
2. Let the DI container do its magic;
3. Success!
For example, one of the subscriber pass tests gets compiled down to [the following](https://gist.github.com/kgilden/dd62730a4b4a65c9bf3b). I'm a bit annoyed by the fact that it's not inlining confiugration creation. Need to investigate this a bit more.
I assumed this was going into v1.3, but feel free to change any of the deprecation stuff as you see fit.

Tag pre-existing Guzzle clients

---

UPGRADE.md
composer.json
composer.lock
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Factory/ClientFactory.php
src/HttpFoundation/StreamResponse.php
src/Resources/doc/available_subscribers.md
src/Resources/doc/configuration_reference.md
src/Tests/DataCollector/GuzzleCollectorTest.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php
src/Tests/Factory/ClientFactoryTest.php
src/Tests/Fixtures/github.description.json
src/Tests/GuzzleHttp/Cache/DoctrineAdapterTest.php
src/Tests/GuzzleHttp/Subscriber/CacheSubscriberTest.php

As mentioned in #24: we want to streamline the cache subscriber's configuration (especially the `csa_guzzle.cache.adapter` configuration.
What we can do for now:
This PR will wait for #25 to be merged, in order to prevent merge conflicts on tests.

Added a simpler way to configure the cache subscriber

---

src/DependencyInjection/CompilerPass/SubscriberPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Factory/ClientFactory.php
src/Factory/DescriptionFactory.php
src/GuzzleHttp/Subscriber/CacheSubscriber.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php
src/Tests/GuzzleHttp/Subscriber/CacheSubscriberTest.php

As mentioned in earlier issues, the Client factory will be deprecated for version 2.0 of the bundle, being replaced by the tag + configurator syntax.

Deprecate client factory

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Resources/doc/clients.md
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Enables class configuration for a specific client. This enables the use of specific clients by the bundle.
E.g.
```yml
csa_guzzle:
clients:
github_api:
config:
class: AppBundle\Client
```
Fixes #36

Feat client class

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
src/Resources/doc/clients.md
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Enables class configuration for a specific client. This enables the use of specific clients by the bundle.
E.g.
```yml
csa_guzzle:
clients:
github_api:
config:
class: AppBundle\Client
```
Fixes #36

Enable client class override

---

src/GuzzleHttp/Cache/DoctrineAdapter.php

The request's body is not correctly serialized since it's a stream, so the key can be the same for requests having just a different body.
Type casting to string resolves the problem.

Fixed cache key

---

src/DependencyInjection/CsaGuzzleExtension.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Hello,
This is a fix in CsaGuzzleExtension to allow symfony services where class instances are used directly from config array.
In GuzzleHttp/Client::__construct(), four keys are expected to be instances of a class.
Namely *message_factory*, *fsm*, *handler* and *adapter*.
My personal use case, required me to extend the _message_factory_ class for some special routines.
This appears to be an oversight in both 1.3 and 2.0 (where only the handler key remains)
Also added some tests for this scenario.
Best Regards,
Khez

Fix CsaGuzzleExtension to allow symfony services

---

.travis.yml

Removed hhvm and php 7 from allowed_failures, as tests pass on all platforms

Disallow build failures for travis

---

src/GuzzleHttp/Cache/DoctrineAdapter.php
src/Tests/Fixtures/response.txt
src/Tests/GuzzleHttp/Cache/DoctrineAdapterTest.php

| Fixed tickets | NA
When we use `PhpFileCache` or `FilesystemCache`, the response will be serialized with the `seriaize()` method, since the `Reponse` object doesn't implement `\Serializable` interface, we're loosing some data as Response body for instance

Fix doctrine adapter

---

src/Resources/views/Calls/call.html.twig

`call.uri` used in `Calls/call.html.twig` view doesn't exist.

Fix profiler call headers

---

src/DataCollector/GuzzleCollector.php
src/Resources/views/Calls/call.html.twig

This PR makes templates a lot more alike between `v1.x` and `v2.x` of the bundle. This will prevent future regressions like the latest merge, where we can find both `url` and `uri` in the `call.html.twig` template.

Made templates more homogeneous between branches 1.x and 2.x

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Resources/config/middleware.xml
src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

Middleware can now be prioritized. The default priority is `0`, and it can be set by using the `priority` property in the `csa_guzzle.middleware` DI tag:
e.g:
```xml
<service id="csa_guzzle.middleware.history" class="Closure">
<factory class="Csa\Bundle\GuzzleBundle\GuzzleHttp\Middleware" method="history" />
<argument type="expression">service('csa_guzzle.data_collector.guzzle').getHistory()</argument>
<tag name="csa_guzzle.middleware" alias="history" priority="-1000" />
</service>
```
Solves #90

Add support for setting a middleware's priority

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php

We had no middleware enabled in production env (no log, no profiler) which results in these errors:
> Warning: array_merge() expects at least 1 parameter, 0 given in /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php on line 71
> Catchable fatal error: Argument 2 passed to Csa\Bundle\GuzzleBundle\DependencyInjection\CompilerPass\MiddlewarePass::registerMiddleware() must be of the type array, null given, called in /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php on line 33 and defined in /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php on line 80

Fix MiddlewarePass when no middleware registered

---

src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

This test is related to an untested edge case, mentioned by @Tobion in #99

Added test for empty middleware array

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

If no middleware is available we can skip this logic. This is relevant when for example no `handler` option is defined. In theory I could have a GuzzleClient subclass that creates a custom handler instead of the default one (`HandlerStack::create`)

Do not set handler when no middleware registered

---

src/Resources/views/Collector/guzzle.html.twig

| Fixed tickets | N/A
When there is no guzzle request. there is a little glitch in the Guzzle Item in the new  WebProfilerToolbar
See :

[RFR] Fixing guzzle item displaying in WebProfiler toolbar

---

src/Resources/doc/clients.md

Add timeout to sample configuration and add a hint that other parameters can be specified similarly to creating HttpClient manually.
| Fixed tickets | -

Hints for HttpClient configuration parameters

---

.travis.yml

Caching the `vendor` directory doesn't look like a good idea to me.
Instead I would cache the downloaded package archives.

fix the Composer cache directory

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Resources/config/middleware.xml

The `setClass()` method from the decorator overrides the service definition (which uses a factory, not a class), and caused the compiler to instantiate the HandlerStack using the following code:
```php
$a = new HandlerStack();
```
instead of:
```php
$a = HandlerStack::create();
```
This caused the default handler stacks from Guzzle not to be added, and as a result it was raising an exception when trying to use the HTTP Client.
This was fixed by replacing `setClass()` with `setFactory()`, which doesn't override the parent service definition but also works around the null class name problem mentioned in d1a46db.
Involved versions:
- Guzzle 6.1
- Symfony 2.7

Fix "No handler set" error from Guzzle's HandlerStack

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Resources/doc/middleware.md
src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

Lets a user disable a specific middleware, by prefixing its name with a `!` character in the client config:
```yml
csa_guzzle:
clients:
github_api:
middleware: ['!my_middleware']
```
Disabled middleware have priority over enabled middleware.

Added possibility to disable specific middleware.

---

src/DependencyInjection/CompilerPass/MiddlewarePass.php
src/Tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php

The guzzle handler can either be a `Reference|Definition|callable` which are now all handled correctly.

Fix MiddlewarePass for handler references and callables

---

src/GuzzleHttp/Cache/DoctrineAdapter.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/GuzzleHttp/Cache/StorageAdapterInterface.php
src/GuzzleHttp/Middleware.php
src/GuzzleHttp/Middleware/CacheMiddleware.php
src/GuzzleHttp/Middleware/HistoryMiddleware.php
src/GuzzleHttp/Middleware/MockMiddleware.php
src/GuzzleHttp/Middleware/StopwatchMiddleware.php
src/Tests/GuzzleHttp/Middleware/CacheMiddlewareTest.php
src/Tests/GuzzleHttp/Middleware/MockMiddlewareTest.php
src/Tests/GuzzleHttp/Middleware/StopwatchMiddlewareTest.php
src/Tests/GuzzleHttp/MiddlewareTest.php

| Fixed tickets | #139 
* Moved each middleware in dedicated classes
* Fixed issue with Stopwatch middleware stopping section already closed, when unwrapping multiple promises with the same URI (Fixes #139)

Refactored middleware

---

src/Resources/views/Calls/list.html.twig

| Bug fix?      | [yes]
When you create another middleware of cache for exemple, time_info is not set and the Collector is break.

Display info only if information is not null

---

src/Cache/DoctrineAdapter.php
src/Cache/MockStorageAdapter.php
src/Cache/NamingStrategy/AbstractNamingStrategy.php
src/Cache/NamingStrategy/HashNamingStrategy.php
src/Cache/NamingStrategy/LegacyNamingStrategy.php
src/Cache/NamingStrategy/NamingStrategyInterface.php
src/Cache/NamingStrategy/SubfolderNamingStrategy.php
src/Cache/StorageAdapterInterface.php
src/GuzzleHttp/Cache/DoctrineAdapter.php
src/GuzzleHttp/Cache/MockStorageAdapter.php
src/GuzzleHttp/Cache/StorageAdapterInterface.php
src/GuzzleHttp/Middleware/CacheMiddleware.php
src/GuzzleHttp/Middleware/MockMiddleware.php

| Deprecations? | yes
This PR moves the Cache logic outside from the GuzzleHttp namespace (except for the middleware).

Changed Cache logic namespace

---

src/Cache/MockStorageAdapter.php
src/Cache/NamingStrategy/AbstractNamingStrategy.php
src/DataCollector/GuzzleCollector.php

#156 added a new header, but the cache naming strategies don't ignore it. Also spotted the `MockMiddleware` response header isn't ignored by default either.
Futhermore, I've switched the header names to use the constants (happy to revert if you'd rather).

Blacklist all Bundle headers, and use constants

---

composer.lock
src/Cache/NamingStrategy/AbstractNamingStrategy.php
src/DataCollector/GuzzleCollector.php
src/DependencyInjection/CsaGuzzleExtension.php
src/GuzzleHttp/History/History.php
src/GuzzleHttp/Middleware.php
src/GuzzleHttp/Middleware/HistoryMiddleware.php
src/GuzzleHttp/Middleware/MockMiddleware.php
src/Resources/config/collector.xml
src/Resources/views/Calls/list.html.twig
src/Resources/views/Calls/macros.html.twig
tests/DataCollector/GuzzleCollectorTest.php
tests/GuzzleHttp/Middleware/HistoryMiddlewareTest.php
tests/GuzzleHttp/MiddlewareTest.php

| Fixed tickets | #185 #184 #164
This ticket reverts the changes brought by @jderusse, and drops support for the correlation ID.
At the same time, this request fixes a few issues with error handling, and brings support for displaying curl errors when they happen. This actually makes debugging much easier, when a request is issued in a `try {} catch {}` statement, and does not throw an error.

Refactored History middleware

---

src/Resources/doc/configuration_reference.md

Listing all logs variables in one place will make it easy for developers to customise logs in yaml settings. I had to search for how to log request and response body so thought this will save someone time to do so :)
Thank you for your great bundle
| Bug fix?      | [yes|no]
| New feature?  | [yes|no]
| BC breaks?    | [yes|no]
| Deprecations? | [yes|no]
| Tests pass?   | [yes|no]
| Fixed tickets | [comma separated list of tickets fixed by the PR]

Added list of all logs variable docs

---

src/Resources/config/collector.xml

I have an application that [uses Twig directly rather than the templating component](http://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen). Currently CsaGuzzleBundle crashes the Profiler / DebugToolbar as it references a template using a syntax that is only supported in the templating bundle.
This allows the profiler to work when used in applications that disable
the templating component and instead use Twig directly.
The rest of the codebase already uses the `@namespace` style.
| Bug fix?      | [yes]
| Fixed tickets | [n/a]

Use Twig namespace when referencing data-collector template

---

src/DataCollector/GuzzleCollector.php
tests/DataCollector/GuzzleCollectorTest.php

Limit CurlFormatter usage for large requests

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/CsaGuzzleExtension.php
tests/AutoconfiguredClient.php
tests/DependencyInjection/CsaGuzzleExtensionTest.php

| Fixed tickets | #225
I am not sure about fixturing services for tests (changes I made in `CsaGuzzleExtensionTest::createContainer`), if we prepare yaml instead I can change it.

Added autoconfigure to configuration to tag client services automatically

---

src/Resources/doc/available_middleware.md

I want to figure out what levels are available during configuring this bundle for `prod`. 
After figuring out, I felt I spend too much time on it that I couldn't resist my urge to make the life of other newcomers to this bundle easier.
| Bug fix?      | [no]
| New feature?  | [no, unless you threat docs as code]
| Tests pass?   | [Very likely yes]
| Fixed tickets | []

Add doc about ability of deciding the level of logging

---

src/DependencyInjection/Configuration.php

refs https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

Avoid deprecation warning when using symfony/config >= 4.2

---

src/DependencyInjection/CsaGuzzleExtension.php
src/Tests/DependencyInjection/CsaGuzzleExtensionTest.php

This PR
| BC breaks?    | maybe
| Fixed tickets | n/a

Fix: Remove cache-related service definitions when cache is disabled

---

.travis.yml
appveyor.yml
composer.json
composer.lock
src/DataCollector/GuzzleCollector.php

| Fixed tickets | N/A
Allow installing bundle with Symfony 5.0
Appveyor fix borrowed from https://github.com/symfony/symfony/commit/6194c2a96c6c8c35de8929a95a3f498941cd1760

Symfony 5 support

---

composer.json

| Fixed tickets |
Guzzle 7.0 is on its way (beta has been released already), and it's basically a non-breaking release that only removes some already deprecated things and bumps deps versions.

Guzzle 7 support
